[package]
name = "Vector-Database-Processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.16.0"
plotters = "0.3.1"
kdtree = "0.6.0"
rand = "0.8.4"